### ISSUE TITLE
Compatibility with Windows 8 / older Windows 10, e.g. 1709?

### ISSUE THREAD

**Issue by Darthagnon** [ALTaleX531/OpenGlass#16]
I currently use an old installation of glass8 on my family's Win10 1709 and Win8.1 machines. Will OpenGlassLegacy work as a replacement?

**Comment by ALTaleX531** [comment]
I have already mentioned in the [README ](https://github.com/ALTaleX531/OpenGlass/blob/legacy/README.md) that only Windows 10 2004-22H2 is supported.

**Comment by Darthagnon** [comment]
> Currently this branch ONLY supports Windows 10 2004-22H2.

I understood the Readme to refer only to the master branch, and a legacy branch also exists, hence why I was wondering whether the legacy branch (given the name legacy) would eventually implement a less narrow support window.

**Comment by ALTaleX531** [comment]
<img width="772" alt="image" src="https://github.com/user-attachments/assets/2c2bf3de-7628-4d09-9ec0-f58f05648e2e">

@Darthagnon 
THE LINK I GAVE YOU WAS ALREADY TO THE LEGACY BRANCH, THEY ARE COMPLETELY DIFFERENT AREN'T THEY? ISN'T THAT CLEAR ENOUGH?

**Comment by Darthagnon** [comment]
> @Darthagnon THE LINK I GAVE YOU WAS ALREADY TO THE LEGACY BRANCH, THEY ARE COMPLETELY DIFFERENT AREN'T THEY? ISN'T THAT CLEAR ENOUGH?

Not really. The support window seems to have changed now, too:
> Windows 10 1809 to Windows 11 23H2

-- from Readme

**Comment by ALTaleX531** [comment]
> Not really. The support window seems to have changed now, too:
> 
> Windows 10 1809 to Windows 11 23H2
> 
> -- from Readme

The version support information which you have requested has been clearly written in the README long before you opened this issue, yet you don't even bother to look at it or the comments I've sent, much less the changelog (for the comment made before you edited it). What's even more ridiculous is that you're still trying to make excuses for yourself even though it's been a long time, how pathetic!

Let's end this here. The legacy branch is named after its implementation, and it's almost impossible to support Windows 11 with this branch of OpenGlass, which means that it's only suitable for legacy versions of Windows and can be easily broken with updates, which is why I didn't add support for older versions of Windows, it's just too much of a waste of time. Of course you could volunteer to migrate it to a very old build of Windows that the master branch will never work on just like glass8, but I'll probably never do that. The master branch is also known as the dcomp branch, which suggests that it is implemented using dcomp technology. Also, the legacy branch has far less functionality than the master branch. Each software has its own rules and basis for naming branches, which varies from developer to developer.

I will pin this issue to remind everyone.
