### ISSUE TITLE
[Legacy Branch] OpenGlass crashes more often after latest PR merge

### ISSUE THREAD

**Issue by ImSwordQueen** [ALTaleX531/OpenGlass#18]
The latest PR merge seems to have brought multiple stability problems to the legacy branch

![image](https://github.com/user-attachments/assets/528d93e9-eca7-439e-8dc4-0afa2be6cfb6)

**Comment by ALTaleX531** [comment]
Please upload the memory dump file according to the instructions in the README, it looks like I may have to refactor the code they wrote.

**Comment by ImSwordQueen** [comment]
due to the size of the memory dump i had to upload it on a different site: https://ninjafiles.io/onO/minidump-2024-07-22-13-49-33.dmp

**Comment by ALTaleX531** [comment]
The memory dump shows that this is the same problem as https://github.com/ALTaleX531/OpenGlass/issues/8#issuecomment-2192911985, which is a crash caused by awm and has nothing to do with the latest pr merge. You can just report it to dulappy.
If I'm not mistaken, there's another bug with awm that initializes multiple times.
