### ISSUE TITLE
[v1.2 on 1809] Blur doesn't get applied on Open Shell's Start menu

### ISSUE THREAD

**Issue by Luximoz** [ALTaleX531/OpenGlass#19]
I've tried with both GlassType=0 and 1 and it seems like it breaks Open Shell's glass opacity

![image](https://github.com/user-attachments/assets/1d9e840e-b943-41bb-822b-8a5b126d2195)

**Comment by ALTaleX531** [comment]
Can't reproduce it, please provide your configuration.

**Comment by Luximoz** [comment]
It's weird because it didn't use to do that when I would use Glass8, anyway, here's the config from the screenshot

https://cdn.discordapp.com/attachments/587259874933473282/1265638402406219891/Windows_7_Aero.xml?ex=66a23d1d&is=66a0eb9d&hm=e1e29d5d79ad46724cfe56a96112756a85158445c5291cc5f9554801e48dc3e0&

**Comment by ALTaleX531** [comment]
What about your OpenGlass configuration?

**Comment by Luximoz** [comment]
![Registry Editor_w1](https://github.com/user-attachments/assets/d52b878d-58f5-47a8-b149-484bba34dfa7)

**Comment by ALTaleX531** [comment]
I guess you don't know what these registry items you added mean, because you added a lot of meaningless items. If you don't want to affect the opacity of the start menu, you just need to set `GlassOverrideAccent` to 0. If I'm not mistaken, when you took that screenshot of the start menu, `GlassType` was 1 and `GlassOpacity` was a value close to 0, which doesn't match the registry screenshot you uploaded.

**Comment by Luximoz** [comment]
Oooooh, I forgot I was testing that value when I first tested OpenGlass lol my bad
