### ISSUE TITLE
FPS monitor in the top right when activated OpenGlass

### ISSUE THREAD

**Issue by TheDolphinSlayer** [ALTaleX531/OpenGlass#21]
I can't for some reason actually screenshot it. But it does disappear when I have games in full screen so its not too big of a deal. It also goes away when I uninstall OpenGlass. I also did compile this one on my own from the legacy branch though.
![Snapchat-1574071477](https://github.com/user-attachments/assets/49a711e7-7819-4062-b4ad-aae82d04e058)
![Snapchat-258944059](https://github.com/user-attachments/assets/064e7311-3fe8-4b17-a94a-8f256cdb19f2)

**Comment by TheDolphinSlayer** [comment]
Update: Using the Legacy build in releases doesn't give me the FPS in the top right, only the legacy branch does. At the cost of losing the button glow lol

**Comment by ALTaleX531** [comment]
![image](https://github.com/user-attachments/assets/2b15679e-0c87-4b4c-b62f-566cdaaec146)
![image](https://github.com/user-attachments/assets/8d972823-1cb2-486e-9d7f-fc5b01233f69)

Compiling a C++ project is quite simple but it's more than just hitting F5. You see the FPS counter because you compiled it with the Debug option, thus activating a series of code blocks for debugging. Not only that, but Debug builds are usually much slower than Release builds.
I don't want to see issues like this in the future, it's a waste of my time to answer them.
