### ISSUE TITLE
Dark windows when hovering over wallpaper.

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ALTaleX531/OpenGlass#22]
https://github.com/user-attachments/assets/3d520aea-1a09-4175-9e95-8aa52c24b08b

Legacy version doesn't do this, but I Like the regular version better.

I am also using 10to7, https://github.com/ImSwordQueen/Win10to7Issues , so something there may be causing it.

This also happens to my taskbar. 
![image](https://github.com/user-attachments/assets/d8610d1e-cba1-4676-be26-9406db6ad8a2)
Startisback++ taskbar that is.

**Comment by ALTaleX531** [comment]
I think it's most likely not a bug, the Legacy branch settings don't exactly work for the master branch, please adjust your settings according to the README. If you still can't fix it, share your settings.

**Comment by ALTaleX531** [comment]
Your OpenGlass settings.

**Comment by N0VA-The-Git-User** [comment]
![image](https://github.com/user-attachments/assets/eab1c8f6-e9b0-431c-925c-1fa42f85ab33)

![image](https://github.com/user-attachments/assets/cee7a504-e744-4ff2-b49a-e2e3ca2f7f5d)

I tried messing with the inactive frames thing and it just reverted back to the original instead

@ALTaleX531

**Comment by ALTaleX531** [comment]
I don't know how glass8's gui works, please don't ask me about that, you should ask bigmuscle.
Instead of just using glass8's gui, you should consider registry editing. I would suggest you to directly check carefully the registry items such as `ForceAccentColorization` mentioned in the README.
If you don't know how to edit the registry, according to what the README says, you should go with DWMBlurGlass instead of OpenGlass, it is not for you.
